apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: default
  labels:
    app: load-balancer
spec:
  type: LoadBalancer
  selector:
    app: blue-controller
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP