Description: >
    Erick Dimistracopulos
    Creates a EKS cluster with CloudFormation
Parameters:
    securityGroupID:
        Description: Security Group ID
        Type: String
    subnetID1:
        Description: Subnet ID 1
        Type: String
    subnetID2:
        Description: Subnet ID 2
        Type: String
Resources:
  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  eksCluster:
    Type: 'AWS::EKS::Cluster'
    DependsOn: eksClusterRole
    Properties:
      Name: capstoneCluster
      Version: '1.17'
      RoleArn: !GetAtt eksClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref securityGroupID
        SubnetIds:
          - !Ref subnetID1
          - !Ref subnetID2