apiVersion: v1
kind: ReplicationController
metadata:
  name: blue-controller
  labels:
    app: blue-controller
spec:
  replicas: 3
  selector:
    app: blue-controller
  template:
    metadata:
      name: blue-controller
      labels:
        app: blue-controller
    spec:
      containers:
      - name: blue-controller
        image: 678583983523.dkr.ecr.us-west-2.amazonaws.com/nginx-hello:latest
        ports:
        - containerPort: 80