apiVersion: v1
kind: ReplicationController
metadata:
  name: blue-controller
  namespace: default
  labels:
    app: blue-controller
spec:
  replicas: 3
  selector:
    app: blue-controller
  template:
    metadata:
      name: blue-controller
      labels:
        app: blue-controller
    spec:
      containers:
      - name: nginx-hello
        image: edimistra/nginx-hello:latest
        ports:
        - containerPort: 80