apiVersion: v1
kind: ReplicationController
metadata:
  name: green-controller
  namespace: default
  labels:
    app: green-controller
spec:
  replicas: 3
  selector:
    app: green-controller
  template:
    metadata:
      name: green-controller
      labels:
        app: green-controller
    spec:
      containers:
      - name: green-controller
        image: 678583983523.dkr.ecr.us-west-2.amazonaws.com/nginx-hello:latest
        ports:
        - containerPort: 80